[workspace]
default-members = ["atspi"]
exclude = ["atspi-codegen"]
members = [
	"atspi-types",
	"atspi",
]

[workspace.dependencies]
atspi-types = { path = "./atspi-types" }
atspi-macros = { path = "./atspi-macros" }
serde = "1.0"
zbus = "3.12"
zbus_names = "2.5.0"
zvariant = "3.12"
