[package]
name = "atspi"
version = "0.3.7"
authors = ["Michael Connor Buchan <mikey@blindcomputing.org>", "Tait Hoyem <tait@tait.tech>", "Alberto Tirla <albertotirla@gmail.com>", "DataTriny <datatriny@gmail.com>"]
description = "Bindings to the Assistive Technology Service Provider Interface over dbus"
license = "Apache-2.0 OR MIT" # For ease of integration in the Rust ecosystem.
readme = "README.md"
repository = "https://github.com/odilia-app/atspi"
homepage = "https://github.com/odilia-app/atspi"
keywords = ["screen-reader", "accessibility", "a11y", "tts", "linux"]
categories = ["accessibility", "api-bindings"]
edition = "2021"

[package.metadata.release]
release = true
publish = true

[features]
# not insane section of features

default = ["async-io", "all-interfaces", "state", "interfaces", "connection"]
async-io = ["zbus/async-io"]
gvariant = ["zbus/gvariant"]
tokio = ["zbus/tokio"]
serde = ["dep:serde"]

# the infamous, insane section of features

all-interfaces = [
	"accessible",
	"action",
	"application",
	"bus",
	"cache",
	"collection",
	"component",
	"connection",
	"convertable",
	"device_event_controller",
	"device_event_listener",
	"document",
	"editable_text",
	"events_document",
	"events_focus",
	"events_keyboard",
	"events_body",
	"events_mouse",
	"events_object",
	"events_terminal",
	"events_window",
	"hyperlink",
	"hypertext",
	"image",
	"interfaces",
	"processed",
	"registry",
	"selection",
	"socket",
	"state",
	"table",
	"table_cell",
	"text",
	"value"
]
events = [
	"events_body",
	"events_document",
	"events_focus",
	"events_keyboard",
	"events_mouse",
	"events_object",
	"events_terminal",
	"events_window"
]
events_document = ["events_body"]
events_focus = ["events_body"]
events_keyboard = ["events_body"]
events_mouse = ["events_body"]
events_object = ["events_body"]
events_terminal = ["events_body"]
events_window = ["events_body"]
events_body = []
accessible = ["convertable"]
action = []
application = []
bus = []
cache = []
collection = []
component = []
connection = []
convertable = ["all-interfaces"]
device_event_controller = []
device_event_listener = []
document = []
editable_text = []
hyperlink = []
hypertext = []
image = []
interfaces = []
processed = []
registry = []
selection = []
socket = []
state = []
table = []
table_cell = []
text = []
value = []

[dependencies]
async-recursion = "^1.0.0"
async-trait = "^0.1.59"
enumflags2 = "^0.7.5"
futures = { version = "^0.3.25", default-features = false }
serde = { version = "^1.0", optional = true, default-features = false, features = ["derive"] }
tracing = "^0.1.37"
zbus = { version = "^3.0.0", default-features = false }

[dev-dependencies]
byteorder = "1.4.3"
