[package]
name = "atspi-types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zbus_names = "2.5.0"
zvariant = "3.12.0"
