[package]
name = "atspi"
version = "0.16.0"
authors = ["Michael Connor Buchan <mikey@blindcomputing.org>", "Tait Hoyem <tait@tait.tech>", "Alberto Tirla <albertotirla@gmail.com>", "DataTriny <datatriny@gmail.com>", "Luuk Duim <luukvanderduim@gmail.com>"]
description = "Pure-Rust, zbus-based AT-SPI2 protocol implementation."
license = "Apache-2.0 OR MIT" # For ease of integration in the Rust ecosystem.
readme = "README.md"
repository = "https://github.com/odilia-app/atspi"
homepage = "https://github.com/odilia-app/atspi"
keywords = ["screen-reader", "accessibility", "a11y", "tts", "linux"]
categories = ["accessibility", "api-bindings"]
edition = "2021"
rust-version = "1.65"
include = ["src/**/*", "atspi-macros/**/*", "LICENSE-*", "README.md"]

[package.metadata.release]
release = true
publish = true

[features]
default = ["async-io", "client-accessories"]
wasm-types = ["dep:wai-bindgen-rust"]
async-io = ["zbus/async-io"]
gvariant = ["zbus/gvariant"]
tokio = ["zbus/tokio"]
client-accessories = ["dep:tracing", "dep:futures-lite"]
unstable-traits = ["atspi-macros/unstable_atspi_proxy_macro", "atspi-macros/tokio", "dep:static_assertions", "dep:async-trait"]

[dependencies]
atspi-macros.workspace = true
enumflags2 = "^0.7.5"
serde.workspace = true
zbus.workspace = true
# optioanl dependencies
futures-lite = { version = "1.12", default-features = false, optional = true }
tracing = { version = "^0.1.37", optional = true }
static_assertions = { version = "^1.1.0", optional = true }
async-trait = { version = "^0.1.59", optional = true }
wai-bindgen-rust = { version = "0.2.3", optional = true }

[dev-dependencies]
byteorder = "1.4"
serde_plain = "1.0.1"
lazy_static = "1.0"
tokio-stream = "0.1"
tokio = { version = "1", default_features = false, features = ["macros", "rt-multi-thread"] }
async-std = { version = "1", features = ["attributes"] }
futures-lite = { version = "1.12", default-features = false }
tokio-test = "0.4.2"
